title: Richard Fritz-Hewer # your name (or website title) here
logo: "/images/IMG-20191129-WA0016.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Student of Data Science working towards a BSc in the subject and striving to supplement academia with as much practical experience as possible.
  <br><br>
  20+ years experience in Data Science and Data Analysis across multiple sectors with a passion for finding new insights in existing data.
  <br><br>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
